# #####################################################################
# Automatically generated by qmake (2.01a) Sun Apr 4 11:11:19 2010
# #####################################################################
TEMPLATE = app
QT += phonon
SOURCES += main.cpp \
    MetronomeWindow.cpp \
    ticker.cpp \
    metronomeconf.cpp
FORMS += MetronomeWindow.ui
HEADERS += MetronomeWindow.h \
    ticker.h \
    metronomeconf.h
